### ISSUE TITLE
[bug] /bin is not in the release as installation instructions state

### ISSUE THREAD

**Issue by dbethke** [newrelic/nri-rabbitmq#13]
##### Description of the problem

Installation directions call for extracting /bin from the release archive, but it is not available in the .zip or the .tar.gz.

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by davidbrota** [comment]
Thanks for letting us know this issue. We provide rpm and deb packages for different OSes.  You can follow this document that will guide you step by step through the whole process:

https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/rabbitmq-monitoring-integration

The zip file is probably a copy of the repo that contains the source code, so it's normal that the /bin directory is missing.
