### ISSUE TITLE
Add hostname and port as attributes

### ISSUE THREAD

**Issue by cpheps** [newrelic/nri-rabbitmq#28]
##### Description of the problem

Hostname and port should be added as attributes on appropriate entities.

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by ccheek21** [comment]
Management API doesn't report host and port, so we can't collect this
