### ISSUE TITLE
Document user permissions required for plugin to function

### ISSUE THREAD

**Issue by kfalconer** [newrelic/nri-rabbitmq#34]
##### Description of the problem

It would have saved a lot of trouble if the rabbitmq user permissions required for the plugin were documented.

See comment here for more details: https://github.com/newrelic/nri-rabbitmq/issues/21#issuecomment-504661575

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by davidbrota** [comment]
Hello @kfalconer,

I've just tested version [2.2.3](https://github.com/newrelic/nri-rabbitmq/releases/tag/v2.2.3) and the integration only collects data from the vhosts specified in the parameter `vhosts`. I'm not getting any error related to missing permissions with the default vhost "/".

Let us know if you still experience this issue with the latest version.
