### ISSUE TITLE
Request: Integrate with RabbitMQs 3.8 prometheus metrics endpoint

### ISSUE THREAD

**Issue by vikinghawk** [newrelic/nri-rabbitmq#75]
## Is your feature request related to a problem? Please describe.
We currently have prometheus scrapping the Rabbit metrics endpoint and using remote write to push these into NewRelic as our long term store. However, this doesn't work well out of the box as many of the erlang_vm* metrics do not map to the correct NewRelic metric types. Additionally, the existing community provided grafana dashboards don't work without some heavy tweaking when using NewRelic as a promql grafana data source do to the lack of support for "on/ignoring" query syntax.

## Feature Description
New Relic RabbitMQ On-Host integration to utilize Rabbit's local prometheus metrics endpoint and push to NewRelic via the metric api.

Nice to have: Recreate some of the community provided Grafana dashboards in NewRelic.

https://www.rabbitmq.com/prometheus.html
https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/metrics.md

## Priority
Nice to Have

**Comment by mangulonr** [comment]
Hi Michael

Thank you for submitting this issue. We're currently working on creating our first integrations based on Prometheus. After these new integrations are released we plan to migrate our existing integrations to Prometheus.
