### ISSUE TITLE
RabbitMQ 3.8 and later should use Prometheus

### ISSUE THREAD

**Issue by lukebakken** [newrelic/nri-rabbitmq#79]
Hello!

I am a member of the RabbitMQ core engineering team. While working on a support case with a customer, they mentioned that they use the New Relic integration, which lead me here to poke around the source code a bit. I notice that this integration uses the HTTP API to collect statistics from the `rabbitmq_management` / `rabbitmq_management_agent` plugins, and I wanted to bring the Prometheus monitoring capabilities to your attention -

https://www.rabbitmq.com/prometheus.html

One of the main advantages of this is that you then can _disable_ the internal stats collection which reduces load on the cluster - https://www.rabbitmq.com/management.html#disable-stats

Please reach out if assistance is needed.

Other related items:

* https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_prometheus/metrics.md
* https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_prometheus/metrics-detailed.md
* https://www.rabbitmq.com/management.html#external-monitoring
* https://blog.rabbitmq.com/posts/2021/05/alerting/
* https://www.rabbitmq.com/monitoring.html

**Comment by carlossscastro** [comment]
Hi @lukebakken,

First of all thanks very much for reaching out to us with this suggestion and the availability to assist us.
We are aware that 3.8+ already exposes native prometheus metrics which is a great addition.

We already did some internal testing on capturing metrics directly from the `/metrics` endpoint which went very well.
We have on our roadmap to work on this at the beginning of our next Fiscal Year.
Still need to do some work on our installation processes for customers who are still running older versions (<3.8)

Anyway we appreciate the useful links and taking time to let us know of this new feature.
We will definitely use your offer for assistance if we run into any issues.

Regards,

**Comment by lukebakken** [comment]
@alvarocabanas does closing this issue mean the feature is implemented? It would help us guide RabbitMQ customers who use New Relic.

**Comment by mangulonr** [comment]
Hi @lukebakken

**Comment by mangulonr** [comment]
Hi @lukebakken 

As my colleague Carlos commented we will work on scraping Prometheus metrics during next Fiscal Year. In the meantime our users should use our actual integration which scrapes telemetry data from the HTTP API.

**Comment by philomory** [comment]
It's now been more than a full calendar year since this was opened, are there still plans to implement this?

**Comment by mangulonr** [comment]
Hi @philomory
As my previous message commented, we plan to migrate Rabbit to Open Standards during the next fiscal year.
What are the reasons why you need Prometheus monitoring in Rabbit?
Is anything preventing you to use our current Rabbit integration?
