### ISSUE TITLE
Add number of queues limit to be monitored to our docs. 

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-rabbitmq#90]
Add number of queues limit to be monitored to our docs. 
https://github.com/newrelic/nri-rabbitmq/commit/6ad81341ed404925141bd820b2f8999840b79e81

We have a static limit of 2000 but we don't specify this limit anywhere in our docs.

**Comment by gsanchezgavier** [comment]
docs pr https://github.com/newrelic/docs-website/pull/12684
